### ISSUE TITLE
Get current object

### ISSUE THREAD

**Issue by williamsousa** [michaelbromley/angularUtils#114]
Hey everybody.

I'm working in project which I need get the current object in pagination.

Let's to example:

In CoffeeScript
<code>
$scope.items = [
{id: 1, text: One},
{id: 2, text: Two},
{id: 3, text: Three},
]

$scope.pageChanged = (obj, id) ->
     console.log obj // ok, this my function return
     console.log id // this is the problem, return undefined
</code>

In Haml:
<code>
.item{"dir-paginate" => "item in items | itemsPerPage: 1", "pagination-id" => "details"}
     %p
          {{item.id}} - {{item.text}}

%dir-pagination-controls{"pagination-id" => "details", "on-page-change" => "pageChanged(items, item.id)", "template-url" => "dirPagination.html"}
</code>

The pageChanged function can't return the item.id parameter.

Hugs.

**Comment by michaelbromley** [comment]
Hi,

Per [the docs](https://github.com/michaelbromley/angularUtils/tree/master/src/directives/pagination#dir-pagination-controls) the `on-page-change` callback will be supplied with a single argument, `newPageNumber`, which is the number of the page being navigated to.

Since you are just displaying one item per page, you can use this number as an index to get the correct object from your `items` collection.

e.g. (plain Javacript cos I don't do coffeescript)

```JavaScript
// your controller
$scope.pageChanged = function (pageNumber) {
    var obj = $scope.items[pageNumber - 1];
    console.log(olj);
}
```

```HTML
<!-- your template -->
<dir-pagination-controls on-page-change="pageChanged(newPageNumber)"></dir-pagination-controls>
```

**Comment by williamsousa** [comment]
Ohh great Michael!

Worked 100%!

Really, thank you so much.
