### ISSUE TITLE
Disqus only loads once

### ISSUE THREAD

**Issue by Maddis1337** [michaelbromley/angularUtils#117]
I am trying to use the [disqus directive](https://github.com/michaelbromley/angularUtils/tree/master/src/directives/disqus), but it only works once for the first page loading. If I switch to other views that also use the disqus directive, it would not include disqus again.

**Comment by Maddis1337** [comment]
I might have solved it by disabling the caching for the state

**Comment by michaelbromley** [comment]
Ah, looks like the same as this issue: https://github.com/michaelbromley/angularUtils/issues/22. Someone proposes a [fix involving using $timeout](https://github.com/michaelbromley/angularUtils/issues/22#issuecomment-51337038) - if you want to try that out rather than disabling cache, then I'd be interested to know if it fixes it for you too, in which case it might be worth incorporating into the directive by default.
