### ISSUE TITLE
Option to just include backward/forward buttons?

### ISSUE THREAD

**Issue by grelas** [michaelbromley/angularUtils#127]
I'm using this angular directive with async. data. However, with the service I'm using, it does not give back a total count. Is there a way to just include the next/prev controls instead of the default 5 minimum pagination links?

**Comment by michaelbromley** [comment]
Yeah, there are a couple of ways you could to this. Since you don't get the total count from your service, you'll just have to use some arbitrary large number, but then you'd need a little guard logic to prevent the user from paging past the end of your result set, of course.

- One option is to edit the template to looks something like this: 

```HTML
<ul class="pagination" ng-if="1 < pages.
    <li ng-class="{ disabled : pagination.current == 1 }">
        <a href="" ng-click="setCurrent(pagination.current - 1)">&lsaquo;</a>
    </li>
    <li ng-class="{ disabled : pagination.current == pagination.last }">
        <a href="" ng-click="setCurrent(pagination.current + 1)">&rsaquo;</a>
    </li>
</ul>
```

- Another option is to not bother using the `<dir-pagination-controls>` directive at all, and implement your own logic in your controller. You can use the `current-page` attribute of the `<dir-pagination>` directive to bind the current page to a $scope variable, and then create a couple of $scope methods to increment/decrement the current page value. In this case, since you wouldn't be using the `on-page-change` attribute of the controls directive, you'd need to put the server-call logic in a $watch of the currentPage value.
