### ISSUE TITLE
Multiple Instances of Custom Directive Using dirPagination

### ISSUE THREAD

**Issue by kyletheninja** [michaelbromley/angularUtils#128]
I have a custom table viewing directive within which I would like to use your pagination directive. My problem is that in order for my directive to be reusable, it needs to set the pagination-ids on its dir-pagination and dir-pagination-controls both dynamically. 

For some reason that I do not understand, the pagination-id attribute of the dir-pagination-controls element is never being evaluated. a simplified version of my custom directive template goes like this.

```html
<div class='interacTable' id='{{metaData.name}}' ng-style='tStyle'>
	<div class='theadContainer' ng-style='theadStyle'>
		<table class='thead'>
			<colgroup>
				<col ng-repeat='col in metaData.cols' style='width: {{col.width}}'></col>
			</colgroup>
			<tr>
				<th ng-repeat='col in metaData.cols'>{{col.name}}</th>
			</tr>
			<tr ng-repeat='headRow in metaData.headRows' class='headRow'>
				<td ng-repeat='col in metaData.cols'>
					<input type=text placeholder='{{getFieldFiller(headRow, col.name, col.type)}}' value=''>
				</td>
			</tr>
		</table>
	</div>
	<div class='tbodyContainer' ng-style='tbodyStyle' >
		<table class='tbody'>
			<colgroup>
				<col ng-repeat='col in metaData.cols' style='width: {{col.width}}'></col>
			</colgroup>
			<tr dir-paginate='rec in data | itemsPerPage: 50' pagination-id="metaData.name + '-pagination-id'" 
						ng-show='rec._isVisible' ng-click="selectRec(rec)" ng-class="rec._style.ngClasses">
				<td ng-repeat='col in metaData.cols' ng-dblClick="editField(rec)">
					<input type='text' value='{{rec[col.id]}}' ng-readonly=isNotSelected(rec) ></input>
				</td>
			</tr>
		</table>
	</div>
	<dir-pagination-controls pagination-id="metaData.name + '-pagination-id'" template-url="templates/dirPagination.tpl.html"></dir-pagination-controls>
</div>
</div>
    
```

In chrome developer tools, it shows that pagination-id is equal to the unevaluated string in the controls directive, though it evaluates properly in the pagination directive. I have tried every way I can imagine to write the string, with and without {{ }}, different ways of quoting, combinations of such, etc. It never gets evaluated. Has anyone else had this problem, and is there a workaround? Or am I doing something wrong. Note that I originally tried with

```html
<dir-pagination-controls pagination-id='metaData.name + "-pagination-id"' template-url="templates/dirPagination.tpl.html"></dir-pagination-controls>
```

and had the same problem.  If I hard code the pagination-id and only put one directive on a page it works properly, but using it that way doesn't help me.

metaData is coming from a rest service wrapped in an angular service, so I thought maybe the timing was off on that variable, however I tried using a variable on my link functions isolate scope and also one on my directive's controller's injected $scope, but none were evaluated as variables when the template was rendered.

**Comment by michaelbromley** [comment]
Hi,

I can see you might have been tearing your hair out over this. Anyway, I took a quick look just now and I think the problem *might* be to do with the fact that you are using a `<tr>` outside of a table.

What I think might be happening is that the browser rejects this as an invalid tag outside of a table, and so it may remove the entire node before Angular has a chance to get to it, compile it and therefore run the `dir-paginate` directive. So when the Angular compiler gets to the controls directive, it looks like there is no corresponding `dir-paginate` to go with it.

Experiment: try using regular table markup instead of divs and see if that fixes it.

If not I'll have to take a deeper look tomorrow some time.

**Comment by kyletheninja** [comment]
Ah, yes that would make perfect sense ~ if I hadn't oversimplified the code too much. I am in fact using a <tr> in a table, which is in a div. The only reason I didn't copy paste my whole template was because I'm not working for myself here and I'm not sure how much actual code I'm allowed to post on the web. I asked though, and updated the question with the whole template as it looks in my code. The expression is actually being evaluated in dir-paginate. However in dir-pagination-controls it is never being evaluated.

**Comment by kyletheninja** [comment]
Ok, there was in fact an easy solution. The dir-pagination-controls directive would only take a single variable, not an expression. I have gotten the behavior I wanted by simply using `pagination-id='metaData.name' ` instead of trying to put the whole expression in there. It is odd that when I tried created variables on my scope to house such an evaluation, they did not evaluate in the proper time course, so if I actually needed an expression in there I would still be a stumped. The weirdest part is that I thought I tried using an extra variable on the isolate scope of my directive just to house a unique pagination-id, but I must have been doing something else wrong.

**Comment by michaelbromley** [comment]
Man, this is a really weird issue! I've just been playing around in Plunker and after a lot of stepping through the Angular source code I realised that there is some weird behaviour caused by having a hyphen in the pagination-id. So if you change it to `pagination-id='metaData.name + "_pagination_id"'`, it seems to work for me. Example: http://plnkr.co/edit/yTDRjewb1T62HbKnbsxE?p=preview

There is something about the way Angular parses expressions that causes it to view a hyphen as a delimiter between one token and the next. This an id of "my-id" is split into two tokens, "my" and "id", which seems to be causing problems here.

Ah - mid composing this answer I saw that you stumbled upon the same thing in a way. So it's not that you can't use an expression - just that you can't use an expression containing hyphens.

**Comment by michaelbromley** [comment]
Actually, it's not that weird at all - Variables referenced in Angular expressions should be valid JavaScript identifiers. As such, you can't use hyphens. The only exception I can think of is if you have an object with a key and use bracket notation. Example:

```JavaScript
// invalid
Hello {{ my-var }}
<input ng-model="my-var">

// valid
Hello {{ my_var }}
<input ng-model="my_var">

// valid
Hello {{ someObject['my-var'] }}
<input ng-model="someObject['my-var']">

// invalid
Hello {{ someObject.my-var }}
<input ng-model="someObject.my-var">
```
