### ISSUE TITLE
ngIf behaves incorrectly for dir-paginate-start/dir-paginate-end

### ISSUE THREAD

**Issue by rmja** [michaelbromley/angularUtils#129]
Consider the following ngRepeat example which works:

    <tr ng-repeat-start="item in items"></tr>
    <tr ng-repeat-end ng-if="item.showDetails"><div ng-controller="DetailsController"></div></tr>

I am trying to convert it to a pagination, but the following does not work:

    <tr dir-paginate-start="item in items | itemsPerPage: 10"></tr>
    <tr dir-paginate-end ng-if="item.showDetails"><div ng-controller="DetailsController"></div></tr>

It complaints that it cannot find the dir-paginate-end.

I then tried to mitigate the error by doing:

    <tr dir-paginate-start="item in items | itemsPerPage: 10"></tr>
    <tr ng-if="item.showDetails"><div ng-controller="DetailsController"></div></tr>
    <tr dir-paginate-end></tr>

But the ngIf is not respected in the sense that `DetailsController` is instantiated no matter if `item.showDetails` is `true` or `false`.

**Comment by michaelbromley** [comment]
Hi,

Yes, there are some strange issues still with the `-start` `-end` syntax that need to be ironed out. As such, certain cases which work with ng-repeat do not work with this. 

It's a very complex problem to solve - I've already spent many hours on this subject due to other issues along these lines (see this issue for further discussion: https://github.com/michaelbromley/angularUtils/issues/92). Right now, I don't have the solution but I plan to give it another go when I get a bit more spare time. 

For now, a possible work-around is to use your second example, but with `ng-show` rather than `ng-if`. That should work because it just hides the row with CSS, rather than taking it out of the DOM altogether (which does not play well with the stuff the pagination directive is doing with the Angular compiler).

**Comment by michaelbromley** [comment]
Please check the latest release which fixes the problems with -start and -end. https://github.com/michaelbromley/angularUtils-pagination/releases/tag/v0.6.0
