### ISSUE TITLE
Pagination IDs conflict with regular IDs

### ISSUE THREAD

**Issue by jondthompson** [michaelbromley/angularUtils#130]
If you use the same string for both a pagination ID and a css ID in your dir-paginate, you'll end up with errors when trying to change pages via the controls.

Either this is a bug, or it should be mentioned in the documentation. I would rather you invisibly add a tag (-paginate) to all of your pagination-ids to make this problem disappear.

**Comment by michaelbromley** [comment]
Hi, 
The css id has no influence on the pagination directive. What I suspect may be happening is that if you use a css id which contains a hyphen (as is a common practice) and then use the same one for your pagination id, the error is actually due to the pagination id being an invalid identifier.

More simply: Variables in an Angular expression must be valid JavaScript identifiers, which means they cannot contain a hyphen. Interestingly this issue just came up yesterday and it took me a while to figure out what was going on. See a code example [here](https://github.com/michaelbromley/angularUtils/issues/128#issuecomment-78516645)

Let me know if that solves your issue. If not, then maybe it *is* a bug and I will eat my words above.

**Comment by jondthompson** [comment]
You’re right. I was using hyphens, and removed them when I made them unique.
-- 
- Jon
