### ISSUE TITLE
ng-paginate: Anchoring and pages

### ISSUE THREAD

**Issue by pasque** [michaelbromley/angularUtils#134]
Is it possible to anchor to content on a page that is not in the current view? For example, you are showing a list of content, with each item having an anchor, but the item you want to show is on a different page than you are currently viewing? I have a search function built into my Angular for people who wish to search throughout the pages, but the reason I ask is if you provide a link from a different page and want to view the content anchored to  and not have the user start at the first page of content. I've searched around and can't find an answer, but I haven't found a definitive "no" either. My tests do show that if the anchor appears on the first page, then you can successfully link to that, just not any items beyond Page 1.

**Comment by michaelbromley** [comment]
If I understand you correctly, you want to be able to link to a list item which may not be on the first page of pagination? 

One way I can think of doing this (I am making some assumptions about the environment since I have little detail to work off):

Given a collection of objects, each with a bunch of properties including and id (which is used for the anchor), you could 

* grab the hash portion of the URL in the address bar using `$location.hash()` 
* this would correspond to the id of the item in the collection you want to go to
* you could find the array index of that item
* then based on how many items you have per page, you can figure out which page that item would appear on.
* set the current-page to that value.

So, in code (untested, just for the idea):

```JavaScript
// assuming your collection is an array in $scope.collection
// URL is something like `http://path/to/app#someAnchorId`
var id = $location.hash();

var targetItem = $scope.collection.filter(function(item) {
    return item.id === id;
})[0];

var index = $scope.collection.indexOf(targetItem);

var targetPage = Math.abs(index / $scope.itemsPerPage);

$scope.currentPage = targetPage;
```

**Comment by vapits** [comment]
Well the:

var targetPage = Math.abs(index / $scope.itemsPerPage);

It's to really a solution as the  result could easily send you to a wrong page (for ex. it will give you results like 1.8, 2.3 etc and even if you round them for a point (depends of the numbers) will send you in wrong page.

I'm working on it to find a solution and if i do i'll share it here (that's why i'm commenting to reopen the issue). 
If anyone else found something please share it.

**Comment by michaelbromley** [comment]
Hi @vapits 

Looking over my example, I see I used `abs` by mistake. Here is a version that should work:

```JavaScript
var id = $location.hash();

var targetItem = $scope.collection.filter(function(item) {
    return item.id === id;
})[0];

var index = $scope.collection.indexOf(targetItem);

var targetPage = Math.ceil((index + 1)/ $scope.itemsPerPage);

$scope.currentPage = targetPage;
```

I modified the demo to incorporate this logic. You can test it by changing the value of the input that says "go to meal id'" - it should take you to the correct page. http://plnkr.co/edit/pOhxr2TmTVitxOvHpLqF?p=preview

**Comment by vapits** [comment]
Hey @michaelbromley 
Yeap that seems a lot better :+1: 

For my task though i used a different approach.

I'm finding the position of the item buy just looking into the active page and log in into localstorage.
Here's my code:

In my page with the pagination i have this on controls and in my controller:
````javascript
localStorage.setItem('activePage', 1);
            $scope.setDatasetPagination = function(pageNumber) {
                localStorage.setItem('activePage', pageNumber);
            };
````
so:
````html
<dir-pagination-controls pagination-id="app.varId" on-page-change="setDatasetPagination(newPageNumber)"></dir-pagination-controls>
````

In the targeted page controller
````javascript
       var currentPage = localStorage.getItem('activePage');
        if (currentPage === null) {
            currentPage = 1;
            localStorage.setItem('activePage', 1);
        }
        $scope.currentPage = currentPage;
````

so i know what page to make active by:
````html
<div dir-paginate="item in items" current-page="currentPage"></div>
````

I hope that will help also :cocktail:
