### ISSUE TITLE
dir-pagination-controls: Using it with Rails

### ISSUE THREAD

**Issue by michaelmendoza** [michaelbromley/angularUtils#143]
I have problems using this with angularjs + rails without copying and pasting the template html file. I use bower-rails to access to the files, and get access to the js file easily. For templates, i use the gem: angular-rails-templates, but html files need to be in the app/assets/template directory. They of course in the lib/assets directory. Any thoughts?

For now I am copying the template file into the app/assets/template directory to get things to work. It would be nice if this package was contained in a single js file, instead of a js + html files. I've seen other packages like angular-ui do this. Just a thought!

**Comment by michaelmendoza** [comment]
After thinking about this I think, since the template you use in 'dirPagination.tpl.html' is so small, in your file 'dirPagination.js' I would just add the template for the dirPaginationControlsDirective as a template string instead of a templateURL like this:

```
            template: '<ul class="pagination" ng-if="1 < pages.length"> \
                        <li ng-if="boundaryLinks" ng-class="{ disabled : pagination.current == 1 }"> \
                            <a href="" ng-click="setCurrent(1)">&laquo;</a> \
                        </li> \
                        <li ng-if="directionLinks" ng-class="{ disabled : pagination.current == 1 }"> \
                            <a href="" ng-click="setCurrent(pagination.current - 1)">&lsaquo;</a> \
                        </li> \
                        <li ng-repeat="pageNumber in pages track by $index" ng-class="{ active : pagination.current == pageNumber, disabled : pageNumber == \'...\' }"> \
                            <a href="" ng-click="setCurrent(pageNumber)">{{ pageNumber }}</a> \
                        </li> \
                        <li ng-if="directionLinks" ng-class="{ disabled : pagination.current == pagination.last }"> \
                            <a href="" ng-click="setCurrent(pagination.current + 1)">&rsaquo;</a> \
                        </li> \
                        <li ng-if="boundaryLinks"  ng-class="{ disabled : pagination.current == pagination.last }"> \
                            <a href="" ng-click="setCurrent(pagination.last)">&raquo;</a> \
                        </li> \
                    </ul>',

```

I am doing this to make it work easily in rails + angularjs. 

Thoughts??

**Comment by pmgower** [comment]
I am considering doing the same thing, Michael, with my current angularjs and .net webapi v2 implementation because i can't seem to get the template file in the right location.

**Comment by michaelmendoza** [comment]
Ya. It makes things easier. 

I also figured out an alternative method which works with rails if you are using angular-rails-templates gem.

Using the orginal code with bower. Another thing you can do so you don't have to modify the source files is you can add this after you initalize your angularjs module:

```
angular.module("templates").run(["$templateCache", function($templateCache) {
  $templateCache.put(
    "directives/pagination/dirPagination.tpl.html", 
    '<ul class="pagination" ng-if="1 < pages.length"> \
        <li ng-if="boundaryLinks" ng-class="{ disabled : pagination.current == 1 }"> \
            <a href="" ng-click="setCurrent(1)">&laquo;</a> \
        </li> \
        <li ng-if="directionLinks" ng-class="{ disabled : pagination.current == 1 }"> \
            <a href="" ng-click="setCurrent(pagination.current - 1)">&lsaquo;</a> \
        </li> \
        <li ng-repeat="pageNumber in pages track by $index" ng-class="{ active : pagination.current == pageNumber, disabled : pageNumber == \'...\' }"> \
            <a href="" ng-click="setCurrent(pageNumber)">{{ pageNumber }}</a> \
        </li> \
        <li ng-if="directionLinks" ng-class="{ disabled : pagination.current == pagination.last }"> \
            <a href="" ng-click="setCurrent(pagination.current + 1)">&rsaquo;</a> \
        </li> \
        <li ng-if="boundaryLinks"  ng-class="{ disabled : pagination.current == pagination.last }"> \
            <a href="" ng-click="setCurrent(pagination.last)">&raquo;</a> \
        </li> \
    </ul>')
}]);
```

**Comment by michaelbromley** [comment]
Hi guys, thanks for the input. There was actually this same issue opened a while back: https://github.com/michaelbromley/angularUtils/issues/88

Someone also submitted a pull request making the same change as discussed here: https://github.com/michaelbromley/angularUtils/pull/138

I hadn't really taken a close look at it since I've been super busy the past couple of weeks. Also, I didn't really understand the concrete use cases which made the current approach problematic. I do now, so thanks for the info to both of you.

So, I agree - let's change this. Thanks @pmgower for the pull request (and @mpkorstanje for the earlier one), but before I go with it I want to discuss the best way of handling this.

### Current suggestions:

1. pmgower suggests in his PR to add a new attribute to the pagination controls, `inline-template`, which is a boolean which, if true, will use an embedded inline version of the template. Without this attribute, the directive will revert to the current behaviour of looking for a path set either by `template-url` or globally via the `paginationTemplateProvider`.

2. mpkorstanje suggests putting the inline template into the $templateCache under a key which matches the default template path (`directives/pagination/dirPagination.tpl.html`) specified in `paginationTemplateProvider`. This means that if the `template-url` attribute is not used, the directive will default to the one set in the `paginationTemplateProvider`, and assuming no other path was set in the config phase, it will find the pre-populated version in the $templateCache.

### My thoughts

1. I'd prefer not to have to add anything to the current API (i.e. the new `inline-template` attribute), to keep things as simple as possible.
2. I like the second idea above in that the inline template in an implicit default, which would make things more "plug and play" - basically harder to mess up.
3. One potential edge-case I can think of with the second approach is that if someone actually has their template located at `directives/pagination/dirPagination.tpl.html`, and specifies this path when configuring the `paginationTemplateProvider`, I'm not sure if this will cause a conflict if the $templateCache already has something registered under that key (i.e. path). Would one overwrite the other?

The third point above could be mitigated by specifying a default path which would be very unlikely to conflict with somebody's real template path, e.g. `dir_pagination_default_template_path`.

Any thoughts?

**Comment by mpkorstanje** [comment]
For #3 I would suggest com.github.michaelbromley.angularUtils.template. You "own" this url.

No additional thoughts beyond what I posted in #138. 

No objections to the proposed changes.

Though I can't really consider myself a stakeholder to this issue any more either. Design was changed to infinite-scroll rather the pagination.

**Comment by pmgower** [comment]
The main reason for my suggested new attribute was to allow for backwards compatibility.  Personally I think if the templateUrl isn't set either in the attribute or in the angular code it should just use the embedded default template.  Since I am not as familiar with your code base I suggested a new attribute; however, if you could think of an easier way to just use the embedded template if the user hasn't configured their own it would make it easier.  Most directives I have used thus far have had their templates embedded (or inline) which makes it easier for the default behavior.  I think it is great that you allow for customization of the template but I couldn't seem to get the path correct which is the main reason for my suggestion.  I think for a general user who doesn't want to customize the template it should just work and that was not my experience.  Perhaps it is my setup but I could not get any of the various paths I tried to work with your template.

So overall I suggest we decide on a way that would allow the "default" behavior to not require to use a template html file at all.  Then you could add an example which shows how to use a custom template.

I found a plnkr that shows how to use a custom template or even the default one but back to my path issue in plnkr it was using the root which is not how I have mine setup.

Just my thoughts.

**Comment by michaelbromley** [comment]
Okay, thanks for your input both of you.

I'm going to use the PR of @mpkorstanje as it is the best fit in that it does not require any changes to the API.

I'll update the bower package too.
