### ISSUE TITLE
DOM manipulations get lost when user navigates next page

### ISSUE THREAD

**Issue by codefullon** [michaelbromley/angularUtils#172]
Hi all,

The page has DOM manipulation actions associated with particular actions that the user performs - thing is, when they go to the next page and come back to the original, those changes are lost - any way by which the state of those manipulations can be maintained?

**Comment by michaelbromley** [comment]
Hi again. I think this won't work automatically, since ngRepeat saves a fragment of HTML that is defined at compile-time and then just uses that fragment to generate new rows.

So any manipulations you perform will not be recorded in the original fragment. As far as I know the only way around this would be to somehow store the state and re-create it when you load the first page again. Sounds painful.

However, you could always show me a bit of your code and maybe I can think of a better way to do it.

**Comment by codefullon** [comment]
thanks @michaelbromley makes sense and actually, I found an alternative wherein instead of DOM, I went the angular way , I kept the manipulation effect pre-populated with a hidden class dependent using ng-class so as soon as i wanted that effect, I changed it by finding that particular row's object (using lodash) and making the ng-class dependent property as true/false as the case might be so since i changed the $scope that i'm using with ng-repeat, the whole thing got solved :-)

cheers again for making dir-paginate, has saved me so so much of time
