### ISSUE TITLE
$index in pagination-id

### ISSUE THREAD

**Issue by Mrudula34** [michaelbromley/angularUtils#190]
Hi Michael,

   When I am using $index in pagination-id like this 
           pagination-id="EmpProjectPagination_{{$index}}"
  It is showing parse error

How to solve that issue, could you please help me.

**Comment by michaelbromley** [comment]
Hi,

Try this instead: `pagination-id="'EmpProjectPagination_' + $index"`

**Comment by Mrudula34** [comment]
Now I am not getting error but index value is not incrementing. For referrence, I have attached an image...

![image](https://cloud.githubusercontent.com/assets/11882955/8572261/1a312228-25a9-11e5-9ec3-d5bc7534a612.png)

**Comment by michaelbromley** [comment]
Where is the `$index` value coming from? I assumed there is some outer ngRepeat but I don't see it in the DOM view in your dev tools.

**Comment by leodsgn** [comment]
I'm having the same error. When I filter the results, it doesn't show some values (doesn't update the $index).

Here some shots...



![normal-list](https://cloud.githubusercontent.com/assets/7218334/8880635/a5d5e7c8-3210-11e5-80c8-aec58047dd33.png)

Here is the normal list.


![filtered-list](https://cloud.githubusercontent.com/assets/7218334/8880655/b6eba7aa-3210-11e5-94b1-116527311575.png)

Then it happens when I put a filter.

![some-items-filtered-list](https://cloud.githubusercontent.com/assets/7218334/8880667/cf489c86-3210-11e5-9ff8-2889211ab9a0.png)



And, here is the code!

![the-code](https://cloud.githubusercontent.com/assets/7218334/8880683/dafd44aa-3210-11e5-83bf-82c65dafdea7.png)

**Comment by kyletheninja** [comment]
I am also getting this error, but am not using $index at all. In my controller I am setting a variable id='tbl-5' or some such string integer combination. It makes me think that it is the number in the paginationId that is causing the problem.

**Comment by kyletheninja** [comment]
I changed the variable I was setting so that the integer was not the end of the name i.e. id='tbl-4-' instead of 'tbl-4' and my problem was solved.

**Comment by kyletheninja** [comment]
Edit - my problem was not solved. The parser parses dashes as minus signs. I actually changed to 'tbl_4' and THAT solved my problem, so it would seem these are separate issues.

**Comment by michaelbromley** [comment]
@kyletheninja Yes, see more on the `-` issue here: http://www.michaelbromley.co.uk/blog/410/a-note-on-angular-expressions-and-javascript-identifiers
