### ISSUE TITLE
page changed function called twice

### ISSUE THREAD

**Issue by NetanelBasal** [michaelbromley/angularUtils#193]
my situation is like this:

1. i have a top filters - when i click on filter i am requesting the new filtered data by call to getData and update  this.FeedService.page = 1 and update the pagination info and the current page.

2. after phase 1 when the numbers of pages in pagination dir change and i click on page 2 for example, the on page change is called twice and i dont understand why this is happening, i am trying to debug this all day and its seems something from the plugin itself.

```html
 <card
            dir-paginate="card in feedCards.FeedService.feed | itemsPerPage: feedCards.FeedService.pagination.items_per_page"
            total-items="feedCards.FeedService.pagination.total_items"
            pagination-id="feedFilter"></card>

  <dir-pagination-controls on-page-change="feedCards.pageChanged(newPageNumber)" pagination-id="feedFilter"
                                     boundary-links="true"></dir-pagination-controls>
```

On filter click:

```javascript
    this.FeedService.page = 1;
    this.SkillsFiltersService.getData();
```

On page change function:

```javascript
pageChanged( page ) {
   console.log('pageChanged');
   this.FeedService.page = page;
   this.SkillsFiltersService.getData();

  }
```

getData function:

```javascript

    this.$http.get(this.appConfig.api.learning).then(( res ) => {
      this.FeedService.feed = res.data.resources;
      this.FeedService.pagination = res.data.control;
      this.paginationService.setCurrentPage('feedFilter', this.FeedService.page);
    });
```

**Comment by michaelbromley** [comment]
Hi,

Thanks for the report. First of all, there are two related issues: https://github.com/michaelbromley/angularUtils/issues/81 and https://github.com/michaelbromley/angularUtils/issues/35. Just want to check you have seen them in case your issue is related. Also make sure you have the latest version.

Looking at the code (https://github.com/michaelbromley/angularUtils/blob/master/src/directives/pagination/dirPagination.js#L272-L306) the `pageChanged` function will be called under two circumstances:

1. when the value of `itemsPerPage` changes.
2. when the value of `currentPage` changes. This will trigger either by clicking a page link, or by changing the value of the current page variable externally (e.g. if you bind to a value on your controller's scope via the `current-page` attribute).

I would start by setting a breakpoint here https://github.com/michaelbromley/angularUtils/blob/master/src/directives/pagination/dirPagination.js#L296 and then when you click to page 2, see which of the two things listed above is triggering the call.

**Comment by NetanelBasal** [comment]
I see the two related issues and it does not help, i will try to do what you suggest and let you know. thanks.

**Comment by NetanelBasal** [comment]
i see from the debugger this:
1. the goToPage() is running.
2. goToPage() is trigger the:
```javascript
   scope.$watch(function() {
        return paginationService.getCurrentPage(paginationId);
      }, function(currentPage, previousPage) {
        if (currentPage != previousPage) {
          goToPage(currentPage);
        }

```
3. goToPage() is calling again.

**Comment by NetanelBasal** [comment]
And now i see its happening when i update the:
```javascript
this.FeedService.feed = res.data.resources;
this.FeedService.pagination = res.data.control;
```

after the xhr.

**Comment by NetanelBasal** [comment]
The $watch who is trigger this function goToPage(currentPage) is called twice, you have a guess why?

**Comment by michaelbromley** [comment]
Here's a guess: perhaps it is because the `this.FeedService.pagination` *object* is being overwritten when you do:

```JavaScript
this.FeedService.pagination = res.data.control;
```

Instead of just replacing the `pagination` object, try individually setting any *primitive* values on the object that need updating, e.g. update the `this.FeedService.pagination.total_items` value (if it has changed), but leave the `this.FeedService.pagination.items_per_page` value intact.

Let me know if that changes anything.

**Comment by NetanelBasal** [comment]
Sorry about the bug report it turns out that the problem was that the server side send me total_items different on changing the page and because of this the on page changed is runs twice. thank you for your answers.

**Comment by michaelbromley** [comment]
Okay, glad you got it solved.
