### ISSUE TITLE
ng-animate ng-leave gets pushed out

### ISSUE THREAD

**Issue by dandrory** [michaelbromley/angularUtils#195]
Hi. 

I love the way the system works but I've found something that I can't seem to fix. 

It has to do with using ng-animate. When I add ng-enter and ng-leave css code to my LI elements in the paginated content it creates a little hickup. Both the ng-enter and ng-leave animations play but the ng-enter Li's that get added trough the pagination are pushing out the ng-leave elements of the previous page. This causes the leave animation to just be instant (and rather ugly) is there a way I can time this out with a delay? It would be good to have a delay filter on the pagination that would do something like this. 

Regards,

Dan

**Comment by michaelbromley** [comment]
Hi Dan,

Any chance you can put together a basic demo of the behaviour you are referring to? Use [the demo Plunker](http://plnkr.co/edit/Wtkv71LIqUR4OhzhgpqL?p=preview) as a basis.

I've not currently got a whole lot of time to handle issues on this project, but a demo would make it more likely I can help out.

**Comment by dandrory** [comment]
http://plnkr.co/edit/d6gDQanFVbzFDDuxIPN9?p=info

I changed the plunker to exactly my code as far as animations go. As you can see when I switch from page it adds the two page lists on top of eachother and displays leaving and entering animations at the same time. I hope that there is a quick fix option that I can do to delay the adition of the second page. So that I can display the animation ->remove old page list -> add new list -> run enter animation (the wrapper div is a fixed height in my website so I wont have problems with the div height going up and down when the list is empty).

Hope this provides enough information.

Regards,

Dan Drory

**Comment by michaelbromley** [comment]
Hi,

Thanks for the demo - made it really simple to try out some ideas.

I've got a CSS-only solution that might work for you. Basically it involves delaying the entire `.archive-item.ng-enter` animation until the outgoing page animations have fully finished. In the case of the demo, that means 0.3s (the transition delay) + 1.0s (0.1s stagger * 10 items). I also set the height to `0` so that they don't initially push the outgoing items down:

```css
.archive-item.ng-enter{
    transition-delay: 1.3s;
    height: 0;
}
```

Here is what it looks like: http://plnkr.co/edit/CpU8b8epC1Y1k3TmKiF7?p=preview

You'll notice that once the second page starts to animate in, the container is stretched. You mentioned that this should not be a problem though, so I didn't bother to fix it. As with anything in CSS, enough time spent hacking on a problem can usually yield the desired result.
