### ISSUE TITLE
Add "paginationService" to the docs

### ISSUE THREAD

**Issue by frankthelen** [michaelbromley/angularUtils#200]
Hi Michael,
 
Al's comment regarding "paginationService" was extremely helpful.
https://github.com/michaelbromley/angularUtils/issues/21#issuecomment-90605968 

I didn't find it in the docs. Would you mind to add it?

Many thanks, 
Frank

**Comment by michaelbromley** [comment]
Yeah that's a good suggestion. I'll do it when I get some time.

**Comment by michaelbromley** [comment]
I thought about this some more and decided that I don't want to document it along side the rest of the API docs, because it is intended as an internal API, which may change with future releases.

If I were to document it, people would start using it widely and then I wouldn't be able to make any changes to it if needed in future without the danger of breaking people's production code.

However, I've added a note about this in a new FAQ section in the docs, so at least it get some mention, along with caveats about its use.
