### ISSUE TITLE
dirPagination: Error when binding to repeated items on same element as dir-paginate

### ISSUE THREAD

**Issue by epelc** [michaelbromley/angularUtils#203]
I'm getting the following error with anything over version `0.6.0` when I have `ui-sref` on the same element as the `dir-paginate` if the `ui-sref` binds any attribute from the `dir-paginate` ie `ui-sref="someRoute({Id:repeatedItem.Id})`. So I don't think it's specific to `ui-sref` but an issue with binding anything using the repeated item from `dir-paginate`.

Here's a plunker demo using `0.8.3` but I found it started happening after `0.6.0` presumably because there was a [rewrite](https://github.com/michaelbromley/angularUtils-pagination/releases/tag/v0.6.0) for `0.6.0`.

http://plnkr.co/edit/dDC17ZQJFyCo5QEExSYv?p=preview

Example error

```
Got a new exception: TypeError: element.setAttribute is not a function
    at forEach.attr (http://dev.*****.com/app/vendor.js:16044:16)
    at Object.JQLite.(anonymous function) [as attr] (http://dev.*****.com/app/vendor.js:16143:10)
    at Object.$get.Attributes.$set (http://dev.*****.com/app/vendor.js:19986:29)
    at link.update (http://dev.*****.com/app/vendor.js:66106:16)
    at Object.fn (http://dev.*****.com/app/vendor.js:66111:35)
    at Scope.$get.Scope.$digest (http://dev.*****.com/app/vendor.js:27465:30)
    at Scope.$get.Scope.$apply (http://dev.*****.com/app/vendor.js:27728:25)
    at done (http://dev.*****.com/app/vendor.js:22855:48)
    at completeRequest (http://dev.*****.com/app/vendor.js:23045:8)
    at XMLHttpRequest.requestLoaded (http://dev.*****.com/app/vendor.js:22986:10) undefined
```

**Comment by michaelbromley** [comment]
Thanks for the report, I'll look into it as soon as I get some time.

**Comment by michaelbromley** [comment]
Just looking in to this now. It looks like it is due to the fact the the `ui-sref` directive does some manipulation to the element it is attached to. Specifically it adds an `href` attribute to the DOM element. 

What seems to be happening is that it is attempting this mutation before the ngRepeat has been rendered. There is an intermediate stage in the rendering cycle where the ngRepeat-ed element is removed from the DOM and replaced with a comment. 

It seems that the `ui-sref` directive is kicking in at this point, and therefore it attempts to add the `href` attribute to what is now a comment node, which cannot be done, hence the `element.setAttribute is not a function` exception.

So.. that makes sense. As for fixing it.. I guess it is a problem to do with order of execution (aka priority) of the various directives involved. Might not be simple to fix. I'll see what I can do....

**Comment by michaelbromley** [comment]
Hmm.. 5 minutes later... I just added `priority: 500` to the definition object of the `dir-paginate` directive, and it seems to fix it.

Seems too easy. Gonna plug it into the test suite and see it is breaks anything else.
