### ISSUE TITLE
dirPagination: ngRepeat with bind-once syntax

### ISSUE THREAD

**Issue by stoppeye** [michaelbromley/angularUtils#204]
My ngRepeats worked fine when using the bind-once syntax as in `ng-repeat="item in ::items"`. However, after converting them to dir-paginate lists, they didn't work anymore (list wouldn't update when clicking the pagination controls). Took me a while to find out that I had to remove the :: to make it work again.
Is this difference between the regular ngRepeat and your directive by design or by mistake? Or am I doing something wrong? For reasons of performance I would really like to keep the bind-once syntax in this particular case.
Thx and great work!

**Comment by michaelbromley** [comment]
Hi,

thanks for the report. I think this may just be correct behaviour in this case. Without the bind-once syntax, moving from one page to the next is causing a re-evaluation of the expression.

When you are binding once, it would only be evaluated on the first render, leading to the behaviour you describe. 

Some things are just not suitable for bind-once, since they need to update during the lifetime of your app. This pagination directive is one of those things.

If performance is a problem, then maybe using bind-once within the paginated items would help, rather than on the list itself.
