### ISSUE TITLE
dirPagination: Make styling easier by adding some classes

### ISSUE THREAD

**Issue by redders6600** [michaelbromley/angularUtils#205]
I feel that the template for this directive should have some semantic classes to help aid custom styling.

I suggest classes like:

- `.boundaryLink`
- `.directionLink`
- `pageNumber`
- `.prev` (for boundary/direction links)
- `.next`

The benefits are mainly for replacing the characters used for left and right (e.g. replacing with icon fonts), but might also be useful for general link styling.

I'd be happy to add a pull request, but since it's such a small change, and CSS class naming preferences vary a lot from person to person, I decided an issue might be easier.

**Comment by michaelbromley** [comment]
Hi,

Thanks for the suggestion. What you describe - e.g. replacing the arrows with icon fonts - sounds like a case for using a custom template.

My idea for the default template is to keep it in line with Bootstrap, and anything that can't be achieved with that markup warrants a custom template, since as you say, different project will have differing naming conventions (e.g. hyphens vs. camcel case vs. underscores).

**Comment by redders6600** [comment]
Ah okay, understood! Happy for it to stay in line with bootstrap then. Thanks!
