### ISSUE TITLE
dirPagination: Question: how to reset pager back to page 1

### ISSUE THREAD

**Issue by gagnechris** [michaelbromley/angularUtils#21]
I've been working with the pagination directive.  By basic setup is a single page which allows the user to enter search criteria and then click search to see the results.  The results are displayed on the same page, below the search input fields.  The pagination is working great, but let's say the user goes to page 3 and then decides to do a new search.  The user changes the search criteria, clicks search again but the pagination controller is never reset to 1...item 3 is still highlighted.

What is the proper way to reset the pagination control back to page 1?  I tried binding current-page  to a var in my scope and reseting that, but that doesn't seem to change state of the pagination controller.

Any ideas?  Thanks!

**Comment by krinkere** [comment]
I believe this was reintroduce in the new version...

**Comment by michaelbromley** [comment]
I'll check it out when I get a bit of free time, thanks.

**Comment by krinkere** [comment]
Actually, I just solved my issue by passing paginationService to my controller and inside of it calling

paginationService.setCurrentPage('paginationId', 1); 

when I do another search.

**Comment by krinkere** [comment]
So that's a work around at least...

**Comment by michaelbromley** [comment]
@krinkere I just had time to take a look, and as far as I can see the issue remains solved. The unit test created for it still passes, and just playing around with the plunker demo, I see that changing the `current-page` scope variable will correctly update the controls.

Do you have any code you can show which isn't working as expected? Or even better, are you able to recreate in Plunker?

**Comment by krinkere** [comment]
I am using several different plugins in my app, so I wonder if something interferes with your code. 

I guess at this point I am just happy that I was able to find a workaround so it is no longer an issue. Thank you for looking into it. 

I will try to post a sample

**Comment by dropfish** [comment]
I'm having the same issue, Michael. I've followed your async example perfectly, but the pagination controls don't update when I change the `$scope.pagination.current` variable in my controller.
![pagination_error](https://cloud.githubusercontent.com/assets/8559734/7426437/f7b1f8d6-ef79-11e4-8103-8b55efc6071c.png)

Otherwise, the directive is awesome--thanks so much for making this!

@krinkere Where/How are you passing the service into your controller? Could you post a code snippet?

**Comment by michaelbromley** [comment]
@dropfish if you are updating `$scope.pagination.current` directly in your controller, then you'll have to set up a $watch on that value to trigger the page change callback. This is because the page change callback is only triggered by a click on a pagination link. In the case that you change the page programatically in the controller, it won't be fired, hence the need for the $watch.

**Comment by dropfish** [comment]
@michaelbromley thanks so much for the fast response. I'm new to Angular, so I'm sorry for the basic questions.

It sounds like I need to set up a $watch in my controller that will do something like this:

`$scope.$watch('pagination.current', function() {
       // call your setCurrent() function
   });`

Is that correct? If so, how can I call your setCurrent() function in my controller? I tried passing the paginationService by name into the controller but it was undefined.

I assume you didn't mean that I need to simply have a $watch on `pagination.current`, seeing as there's already one implicitly created because I'm using it in my template: `{{ pagination.current }}`.

Thank you for your help, I greatly appreciate it!

**Comment by michaelbromley** [comment]
Yeah, you're on the right track. If you have followed the async example from the docs, you should have a scope method that you are passing in to the `on-page-change` attribute. In the example, it is ` $scope.pageChanged()`.

You can just use this as the $watch callback:

```JavaScript
$scope.$watch('pagination.current', function(val) {
  $scope.pageChanged(val);
});
```

You don't need to use the internal components such as the paginationService.

... Actually now that I'm taking a closer look at that example, I think there is an error with it. I missed off the `current-page` attribute from the `dir-paginate` directive. It should look like this:

```HTML
<tr dir-paginate="user in users | itemsPerPage: 25" total-items="totalUsers" current-page="pagination.current">
```
 See if that works for you.

**Comment by dropfish** [comment]
You're the man! Got it working by adding the `current-page` attribute. I can't believe how quickly you responded and helped me, that's so awesome :)

**Comment by samirshah** [comment]
I am facing same issue can anyone please please provide me working plnkr.

**Comment by dropfish** [comment]
@samirshah I've modified Michael's plunkr to include a `resetPage()` function that resets the `currentPage` variable to 1. You can test it by clicking on any page other than 1 and then clicking the "Reset Page" button I added. Here's the [forked plunkr](http://plnkr.co/edit/z3Gl6uBnC34cQiEyeInm?p=preview).

If you're having trouble implementing this in your code, make sure you're adding the `current-page` attribute to your `dir-paginate` directive (not in the pagination controls). Hope this helps!

**Comment by michaelbromley** [comment]
@dropfish thanks for the Plunker demo - should be useful to others with the same question.

**Comment by shalizi** [comment]
Micheal,
Is there a way to search on the current page, if I were to be on page 5, this way the search does not default to page 1 and only search within page 5 until it is directed to go else where. Please advice

**Comment by michaelbromley** [comment]
@shalizi If you mean you want to filter only the results on that page, then yes, this should be possible by putting the `filter` filter after the `itemsPerPage` filter. e.g.:

```HTML
<input ng-model="q">
...
<li dir-paginate="item in collection | itemsPerPage: 10 | filter: q" current-page="myCurrentPage">
```

**Comment by shalizi** [comment]
I will try this, I hope this works. Regardless, THANK YOU for helping.

**Comment by shalizi** [comment]
Michael,
Search is still a bit off, I don't even mind having it search either
current page or entire list. The only thing that I'm doing different, I'm
using div's instead of li's with ng-repeat. I don't think this should
create any issues since ng-repeat works the same way with any element but I
could be wrong. I'm not sure what to make of it. Thanks for helping.

Ahmad:

**Comment by shalizi** [comment]
Hi,
Sorry, I don't mean to bombard you with all these emails but I thought I
send you this one. This way you don't have to look into something that is
not broken. Everything is working good. My situation was a bit complicated,
I'm using ng-repeat with div's, forms, and tables all at the same time and
after making sure all elements were properly terminated.. everything works
smoothly, thank you for putting together a very robust pagination program.

Ahmad:

**Comment by michaelbromley** [comment]
@shalizi Thanks for the update. Glad you got it sorted.

**Comment by Geek2017** [comment]
it dont work need help pls

**Comment by Sardar-Ali-Murad** [comment]
https://embed.plnkr.co/z3Gl6uBnC34cQiEyeInm

**Comment by Fruitless5** [comment]
Here’s what I suggest



https://stackdev.space/questions/displaying-just-the-initial-ten-items-with-angularjs-and-dir-pagination-controls
