### ISSUE TITLE
dir-paginate in Accordion

### ISSUE THREAD

**Issue by Jebedo** [michaelbromley/angularUtils#229]
I have problem with angular ui-accordion with dir-paginate.

This code won't work for me:
 ```html
 <div ng-controller="testController">
   <accordion class="panel-group accoridon grey">
      <accordion-group dir-paginate="item in friends | itemsPerPage: 1" pagination-id="testLst">
        <accordion-heading>{{item.name}} </accordion-heading>
      </accordion-group>
    </accordion>
     				
 <!--  <div dir-paginate="item in friends | itemsPerPage: 3" pagination-id="testLst">{{item.name}}</div>-- >
 			
 <dir-pagination-controls pagination-id="testLst" ></dir-pagination-controls>

 </div>
```
`Error: [$compile:ctreq] http://errors.angularjs.org/1.4.5/$compile/ctreq p0=accordionGroup&p1=accordionTransclude at Error (native)`

But Plunker works :( :
http://plnkr.co/edit/06O3Uh7JrK9rH8szQvT7?p=preview

Is there some library combination that I got wrong?
Mine is:
Angular 1.4.5
Angular ui-bootstrap tpls 0.13.4.

**Comment by michaelbromley** [comment]
The fact that it works in Plunker shows that it *can* work at least. So there must be something present in your actual code which is interfering somehow. Do you have any other directives on the in accordian-group or accordian-heading elements? Sometimes errors arise due to conflicts in the order of compilation of various directives which don't play well together.

**Comment by Jebedo** [comment]
So I got it to work. The problem seems to be in javascript dirPagination.js itself. When I c/p it from Plunker it works, but when I c/p it from web page there was that strange error. 

I probably c/p wrong :)

Problem is solved, topic can be closed.
