### ISSUE TITLE
dirPagination: Jump to user requested page

### ISSUE THREAD

**Issue by sabin-iliescu** [michaelbromley/angularUtils#240]
Hi Michael,
I've got the pagination library to work with my site, it's working great, thanks for the library.

When the user clicks the middle input of the bellow pagination and enters a page number I want it to be able to jump to a certain requested page on blur of that input.  
![dir-pagination](https://cloud.githubusercontent.com/assets/5187970/10245133/79627894-690d-11e5-8263-9a377587bfb0.png)

Maybe you could give me some advice and some best practices in developing this feature.  
Tahnk you.

**Comment by michaelbromley** [comment]
Hi,

Since this will require some special logic, I think you'll have difficulty implementing it as a simple custom template for the `dir-pagination-controls` directive.

Instead, I would either implement the logic directly in the parent controller, or (better for re-use) encapsulate it in a custom directive. Implementing the forward and backward arrows are just a matter of changing the variable bound to the `current-page` attribute. Setting the page based on user input would likewise just be a matter of setting the current-page value, albeit with some guard logic in there to ensure the page is valid.
