### ISSUE TITLE
Checkbox selection gets carried to the next page

### ISSUE THREAD

**Issue by PKudupu** [michaelbromley/angularUtils#245]
When I check a row in the current page it gets carried to the next page. Can you please help with this issue
<th class="checkAll">
                                <div>
                                    <input type="checkbox" ng-model="isAll" ng-click="selectAllRows()" /> <i class="fa fa-trash-o fa-2x" ng-click="removeSelectedRows()"></i>Remove
                                </div>
                            </th> 
<tr class="rowclass" dir-paginate="enrollment in enrollmentList |orderBy:sortKey:reverse|filter:suspendedSitesearch|itemsPerPage:5">

 <dir-pagination-controls max-size="2" direction-links="true" boundary-links="true"> </dir-pagination-controls>

**Comment by PKudupu** [comment]
![pagination2](https://cloud.githubusercontent.com/assets/11841494/10456537/ed5f1b78-718f-11e5-876f-0d252c6a78c5.PNG)
![paginationerror1](https://cloud.githubusercontent.com/assets/11841494/10456536/ed5cbf40-718f-11e5-8f6c-7350b5044fff.PNG)

**Comment by michaelbromley** [comment]
Could you paste some code? Hard to help from just the screenshot.

**Comment by PKudupu** [comment]
http://plnkr.co/edit/gLSc7nfKhHT7IfO5x3vP?p=preview
I have the code pasted in plunker. Not sure why I am not able to use paginate in plunker.
Thanks in advance
Prathap Kudupu

**Comment by michaelbromley** [comment]
Hi,

Here is a working version of your plunker: http://plnkr.co/edit/ZH2hjjcblptdbJhSfXau?p=preview

The basic problem was this:

```HTML
<input type="checkbox" ng-model="tableSelection[$index]" />
```

Since the `$index` var refers to the index on *that page only*, so the first item on page 1 has index 1, and so does the first item on page 2, page 3, etc.

In order for your proposed hash-based system to work, you need to make sure the keys are unique to each item in the collection. For example, assuming the `studentNo` value is a unique ID, you could use this as the basis for your `tableSelection` hash, e.g.:

```HTML
<input type="checkbox" ng-model="tableSelection['id_' + enrollment.StudentNo]" />
```

Hope that helps.

**Comment by PKudupu** [comment]
Thanks a ton.
I appreciate taking time out of your busy schedule.
Regards
Prathap Kudupu

**Comment by michaelbromley** [comment]
No problem. I'll close this issue then.

**Comment by agriboz** [comment]
Have you ever tried with `ng-options`. It can't find the right way to how to handle this situation.

http://plnkr.co/edit/0YoVkv2hR0uM6H5b4xIA?p=preview
