### ISSUE TITLE
dirPagination: get element's page number 

### ISSUE THREAD

**Issue by yvesmh** [michaelbromley/angularUtils#259]
Hi,

Is there any way to get the page number of an element in my `dir-paginate `? 

The use case I have for this is  moving the `current-page` after removing items from the table if the items removed were in previous pages. So say I selected all items in page 1, 2 and 3, and now I'm in page 4 and hit a "delete all selected items" button, I want to move the current page to 1 instead of leaving it at page 4.

How I plan on doing this is getting the number of items that were deleted in previous pages so I can move the page accordingly.

 How can I get this number?

**Comment by michaelbromley** [comment]
Hi,

I don't know your exact set-up, but can you not just calculate it? Since you know how many items per page there are, and you can get the index of the element (e.g. with `myCollection.indexOf(element)`). 

In the scenario of deleting all items in the first 3 pages, if you actually remove them from the collection I think the pagination should automatically update itself in the way you intend. Is this not actually the case? Can you put together a plunker demo based on this: http://plnkr.co/edit/Wtkv71LIqUR4OhzhgpqL?p=preview ?

**Comment by yvesmh** [comment]
Hi,

Yes, I  figured out how to calculate it, my problem was getting the sorted and filtered array reference, but I found out how to create and auto-update it using a syntax like this in the view:

```html
<tr dir-paginate="item in itemsInPage = (sortedItems = ( totalItems | orderBy:sort.sortingOrder:sort.reverse)  |  itemsPerPage: itemsPerPage)" 
   current-page="currentPage">
```

Then to get the page number:
```javascript
function getItemPage(item) {
  var index = $scope.sortedItems.indexOf(item);
  var pageNumber = Math.floor(index / $scope.itemsPerPage) + 1;
  return pageNumber;
}
```
Thanks!
