### ISSUE TITLE
Same comments showing up on multiple pages

### ISSUE THREAD

**Issue by isbara** [michaelbromley/angularUtils#260]
Hii thank you for this module. I want to use this but I am stucked right now. I dont know how to solve this. I look into this page:
https://help.disqus.com/customer/portal/articles/662547-why-are-the-same-comments-showing-up-on-multiple-pages-

My identifier and url both unique. Something else cause this.

    <dir-disqus disqus-shortname="mangayurdu"
         disqus-identifier="{{ manga.ad }}"
         disqus-url="http://mangayurdu.com/icerik/{{ manga.ad }}"  // Is this disqus url disqus iframe going to show url or this url:mangayurdu.disqus.com
		 disqus-title="{{ manga.ad }}">
    </dir-disqus>

Are we adding this below line to body tag?

    <script>
    (function() { 
        var d = document, s = d.createElement('script');
        
        s.src = '//mangayurdu.disqus.com/embed.js'; 
        
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
     })();
    </script>
![ss 2015-11-13 at 12 30 34](https://cloud.githubusercontent.com/assets/7198374/11133330/e18d1b4e-899d-11e5-9a29-d055188cbbbf.png)

See duplicate comment:
http://mangayurdu.com/icerik/Bleach
http://mangayurdu.com/icerik/Berserk

**Comment by michaelbromley** [comment]
Hi,

This is just a guess: is your data available in the `scope.manga` object at the time that the directive is used? If, for example, that data is loaded async, it will initially be `undefined`. That might make Disqus think they are the same page, since they are both undefined. If this is the case, take a look at the [read-to-bind](https://github.com/michaelbromley/angularUtils/tree/master/src/directives/disqus#ready-to-bind-attribute) attribute.

**Comment by michaelbromley** [comment]
Closing. Please re-open if this is still an issue.

**Comment by NetanelBasal** [comment]
Hey, did you solve this problem?
