### ISSUE TITLE
If you use interpolation in the displayName it is not shown if you use breadcrumbProxy

### ISSUE THREAD

**Issue by GustavSt** [michaelbromley/angularUtils#261]
I edited the plunker to demonstrate this issue
http://plnkr.co/edit/4LhjUzVAmGNaihW4TAVF?p=preview

The `home.users`-state uses proxy to show the `home.users.list`-state. the `home.users.list`-state use resolve and interpolation to show info in the breadcrumb. This is however not included in the breadcrumb in the `home.user.details` state.

It works perfectly when not using proxy, as show in the example (the home state).

**Comment by michaelbromley** [comment]
Okay. Thanks for the Plunker demo -clearly illustrates the issue there. I looked into it briefly, but unfortunately do not have a lot of time to put into this right now.

If you feel up to investigating for yourself, a pull request or even advice on how to fix would be appreciated. Otherwise I'll try to get round to it when I get a bit more free time.
