### ISSUE TITLE
How to splice the last item in last page?

### ISSUE THREAD

**Issue by immma** [michaelbromley/angularUtils#278]
I'm not sure how to splice in dirPaginate, everything just work fine, but for the last item in last page I found that the item is not really splice. If I use database for splicing, actually it works fine, but not for the "repeat" (angular repeat). it has no change when I splice it. 

Based on your code in plunkr, I try to make a splice function.
http://plnkr.co/edit/CiyaGJ8ObNY4m1jREISg?p=preview

these code above, the last item in the last page is "meal 100: crisp butty drizzled with cheese sauce". When I splice it, it actually works, but the "meal 100: crisp butty drizzled with cheese sauce" item not gone. 

very warm regards, 
Immanuel hanitya.

**Comment by michaelbromley** [comment]
Hi,

This is just because your splice logic is faulty. You are using the following code in your template: `ng-click="slicing($index)"` - in this case, the `$index` var provided by ngRepeat refers to the index *on that page only*, rather than the index in the whole collection.

So, if you are on page 3, and try to splice the second item on that page, you will notice that the value of `$index` is 1. You then do `$scope.meals.splice(index, 1);`, which will remove the second item of the entire collection, when in fact you want to remove the second item on the third page.

So, you just need to take into account the current page and the value of itemsPerPage. This will allow you to calculate the correct index to splice in the collection.
