### ISSUE TITLE
URL Hash Change on Page Change

### ISSUE THREAD

**Issue by JeanHules** [michaelbromley/angularUtils#302]
I can't find a solid answer to this, but I think it would be helpful if some gave a go to answer for this.

Basically what I am looking for is when I go to page 2, the url changes to url.com?page=2.

This I accomplished by 
```
$scope.pageChanged = function(pageNumber) {
  $location.search({page: pageNumber});
  updateQueryString({
    page: pageNumber
  });
};
```

The issue I am having is when I click back, the URL changes, but the content and the number bar at the bottom does not update. 

I came up with the code below, but am having issues with setting the $scope.currentPage within the watch. Any ideas:

```
   //Detect page param and set the currentPage to that on page load.
    if($location.search().page){
        $scope.currentPage = $location.search().page;
    }

    //This doesn't seem to work, but the idea here is on change of page param, it will set the currentScope to that param.
    $scope.$watch(function(){ return $location.search() }, function(params){
        if($location.search().page){
            $timeout(function() {
                $scope.currentPage = params.page;
            });
        }
    });
```

**Comment by michaelbromley** [comment]
Hi,

Your solution is conceptually fine. Since we cannot use routing to take care of this, we do need to wire up the $watch ourselves.

Looking at your code, I think the $watch is not working because your watch function returns the `$location.search()` object. The Angular change detection is performing an equality check based on object reference, and is seeing the same object reference each time, so is not triggering the handler. For more detail see: http://stackoverflow.com/a/19455564/772859

Try either:

1. returning `$location.search().page`, which will compare the value rather than the reference.
2. setting the third argument to `true`. This solution is theoretically less performant than the first however.

In either case, you shouldn't need the `$timeout`.

**Comment by philippguertler** [comment]
`$location` broadcasts events whenever the URL changes (also fires when the user presses back).
You can watch these events with `$scope.on(...)`. Here is an example:
```
$scope.$on('$locationChangeSuccess', function(){
        if($location.search().page){
                $scope.currentPage = params.page;
        }
    });
```

See https://docs.angularjs.org/api/ng/service/$location for more information on the events.
