### ISSUE TITLE
$index is fixed for all pages using dir-paginate

### ISSUE THREAD

**Issue by shankarregmi** [michaelbromley/angularUtils#341]
I am using dirPaginate directive for pagination in my Angular App. its working fine but the problem is I am showing 10 records per page but on every page the $index is repeating same (1-10) on each page. it should be 11-20,21-30 and so on for the next pages.

I made to work it in a hackish way by 
```<td>{{(currentPage*10 - 9)+ $index}}</td>```

But the problem is when I change the itemsPerPage above solution does not work
![screenshot from 2016-04-19 09 37 02](https://cloud.githubusercontent.com/assets/7703345/14627258/627c0e5e-0612-11e6-979f-f0cff6886a52.png)

Is there any way I can access `range.lower` in my controller 
```<dir-pagination-controls template-url="admin/views/shared/dirPagination.tpl.html" on-page-change="getIndexCount(range.lower, range.upper)"></dir-pagination-controls>```

I get both `undefined`

**Comment by michaelbromley** [comment]
Hi,

The fact that `$index` resets is the expected behaviour of ngRepeat - which has no concept of which page it is on - it just repeats the collection we provide for that single page.

There is no simple way to get hold of the `range` object outside the template, but [if you look at the source](https://github.com/michaelbromley/angularUtils/blob/a4283668760fb537c1468755463432c3be0efef2/src/directives/pagination/dirPagination.js#L391-L393), to calculate those values is extremely simple.

Also, your code for figuring out the index is *almost* exactly what you need - just modify it to take into account `itemsPerPage`:

```html
<td>{{ ($index + 1) + (currentPage - 1) * pageSize }}</td>
```

See further discussion here: https://github.com/michaelbromley/angularUtils/issues/76#issuecomment-61810215

**Comment by shankarregmi** [comment]
Thanks, I just added `$index` as :
```  <td>{{(currentPage - 1) * pagination.perPage + $index+1}}</td>```
