### ISSUE TITLE
Pagination Controls Dissapears when hiding and showing elements

### ISSUE THREAD

**Issue by firomero** [michaelbromley/angularUtils#346]
Having a paginated table at some point the table is hidden and show a different section and when the table is showed back pagination controls are gone. Directive is in HTML, but no controls showing navigation links

**Comment by michaelbromley** [comment]
Hi. I'm afraid this issue is far too vague for me to help on. Please, [read the issue template](https://github.com/michaelbromley/angularUtils/issues/new) and try to provide more information - as much as possible.

I'm going to close this issue, but feel free to re-open if you are able to provide sufficient detail for me to work with.
