### ISSUE TITLE
dirPagination: Cannot access scope method in dirPagination.tpl.html

### ISSUE THREAD

**Issue by mparman6** [michaelbromley/angularUtils#348]
Hello,

I might be trying to do something that is impossible, but I thought I would ask anyway.
I made custom template for the pagination controls, code below:

```
<div>
<a id="backlink" class="waves-effect waves-light btn" ng-click="(pagination.current == pages[0]) ? setCurrent(pagination.last) : setCurrent(pagination.current - 1)">Previous Material</a>
<a id="nextlink" class="waves-effect waves-light btn" ng-click="nextMaterial();(pagination.current == pagination.last) ? setCurrent(pages[0]) : setCurrent(pagination.current + 1)">Next Material</a>
</div>
<br>
```
In the same view as the pagination controls, I have a controller with a method I am trying to call with ng-click inside the pagination controls. You can see that in the second <a>, with the nextMaterial(). 

I am expecting that, upon clicking, the method will be called. However, nothing happens. No errors. Is it impossible to access the controller scope from within the pagination controls template?

My controller method:

```
$rootScope.nextMaterial = function() {
			$scope.next = newArray[offset - offset + nextCounter].material_name;
			previousCounter++;
			$scope.previous = newArray[previousCounter + 517].material_name;
		}
```
Note: I've used both $scope and $rootScope, it just happens to be $rootScope right now. Same results.

Elements in view I am trying to change:

```
 <div>
            <!-- show previous page material_name -->
            <p id="backMat">{{ previous }}</p>
            <!-- show next page material_name -->
            <p id="nextMat">{{ next }}</p>
          </div> 
```

**Comment by michaelbromley** [comment]
Hi,

You are right - this is impossible ;)

The reason is that the `pagination-controls` uses an isolate scope, which means that any outer scopes (those of parent controllers, for example) are not visible within the isolate scope.

You can still achieve the desired result (if I understand your code correctly) by using the `on-page-change` callback ([see docs](https://github.com/michaelbromley/angularUtils/tree/master/src/directives/pagination#dir-pagination-controls) and then figuring out whether the user has gone forwards by inspecting that values of `newPageNumber` and `oldPageNumber`.
