### ISSUE TITLE
dir-pagination-controls: not hiding when scope variable is reset

### ISSUE THREAD

**Issue by aroach** [michaelbromley/angularUtils#351]
**Description of issue**:

I'm trying to implement a search page with the results being paged through your directive.  It's working great except when I try to reset the search page.  Thanks in advance!

**Steps to reproduce**:

Update the ng-repeat array to a null value.

**Expected result**:

`<dir-pagination-controls>` would hide since the array is null.

**Actual result**:

pagination controls remain even though array is null.

**Demo**:
http://plnkr.co/edit/m1DJvbPWH8THP3R8L1Jx?p=preview

**Comment by michaelbromley** [comment]
Is there a particular reason why you want to set the collection to `null` rather than `[]` (empty array) to reset it? Setting it to `[]` should work as desired.

The reason can be seen in [this line of code](https://github.com/michaelbromley/angularUtils/blob/6055d260be44c0ba221a8c9bea015ac97e836a10/src/directives/pagination/dirPagination.js#L102) - if `collection === null`, then it is falsy and the `setCollectionLength` method does not get called, which means the pagination controls do not get updated.

**Comment by aroach** [comment]
@michaelbromley no reason other than ignorance.  :-)  thx!  that worked!
