### ISSUE TITLE
Multi-level pagination support

### ISSUE THREAD

**Issue by ithillel** [michaelbromley/angularUtils#353]
Hi

For example, let's take this fragment

            <div ng-repeat="lang in langs">{{lang.id}} 
              <div class="panel-body">
                  <p dir-paginate="drink in lang.drinks | itemsPerPage: pageSize" pagination-id="lang.id">{{ drink }}</p>

                  <dir-pagination-controls pagination-id="lang.id"  template-url="dirPagination.tpl.html"></dir-pagination-controls>
              </div>
            </div>

Here langs is array which contains complex objects(with id and drinks attributes). If id is numeric value then this fragment gives an error: "Error: [$parse:syntax] Syntax Error: Token '__currentPage' is an unexpected token at column 2 of the expression [1__currentPage] starting at [__currentPage]."

If id is text then everything is OK.  I tested on you Plunker demo version(but use Angular 1.3.13).

**Comment by michaelbromley** [comment]
Hi,

This is expected behaviour. An angular expression variable conforms mostly to the rules of any JavaScript identifier. In this case, it is illegal for an identifier to begin with a number. See this article for more detail on this topic: http://www.michaelbromley.co.uk/blog/410/a-note-on-angular-expressions-and-javascript-identifiers

A solution could be to prefix with a valid character = e.g. an underscore:

```
pagination-id="'_' + lang.id"
```
