### ISSUE TITLE
Paginated links are not sharable after pagination

### ISSUE THREAD

**Issue by riginoommen** [michaelbromley/angularUtils#362]
**Description of issue**:
How to make the links sharable after paginating the page something like [http://test.com/#/application?page=2]

If the sharing is possible give an update in the wiki otherwise consider this as a feature request

**Comment by michaelbromley** [comment]
This is something you need to figure out and implement yourself, since it is highly dependent on the app in question - your url scheme, whether you use html5 mode and so on.

Here is an example of how you might want to approach the problem: https://github.com/michaelbromley/angularUtils/issues/295#issuecomment-184176784
