### ISSUE TITLE
Loading on pagination

### ISSUE THREAD

**Issue by ashokgavini** [michaelbromley/angularUtils#394]
i need a loading icon when page is changing from one page to another page ...

Ex:
1 to 5.

intially at 1. Now i need to go to page 5.when page is changing from 1 to 5 i want to show loading image or icon.
------------------------------------------------------------------
another issue:

how to highlight text in result expression that what we search in textbox.

Please Help me michaelbromley....

**Comment by michaelbromley** [comment]
Hi,

This looks like a general support request rather than an issue specifically related to this project. Unfortunately I don't have time to field such requests, and a better source of assistance would be [StackOverflow](http://stackoverflow.com/).

If you think I've made a mistake and this is indeed an issue specific to this project, please re-open the issue and include further detail.
