### ISSUE TITLE
on-page-change is being called after a new search (causing a double query)

### ISSUE THREAD

**Issue by augustjared1** [michaelbromley/angularUtils#403]
I have a lot of pages that are generic api paging requests that include a search field. When I do a search, and then use the paging at the bottom of the paginated section, everything is fine. But if after I use the pagination and then do a new search, the search is called 2 times. Once by the search button (which is correct) and also by the on-page-change in the dir-pagination-controls. The double call is only made if a new search is called after the on-page-change has already been called to change the pagination page.

Code Example is below

**HTML**

``` html
<div class="row item-table-row hover-div decaStripingEven" paginate="taskOrder in taskorderCollection | itemsPerPage: 15" items="totalTaskOrders" current-page="filters.pageNumber">
**generic ng-repeat data listed here**

        <div style="padding: 15px">
            <dir-pagination-controls on-page-change="pageChanged(newPageNumber)"></dir-pagination-controls>
        </div>
```

**JavaScript**

``` JavaScript
                filters: {
                    search: "",
                    pageNumber: 1,
                    pageSize: 15,
                    sortColumn: "strTaskOrder_num",
                    sortDirection: "ASC",
                },
 getTaskOrders: function (page) {
                    $scope.filters.pageNumber = page ? page : $scope.filters.pageNumber;
                    taskOrder.query($scope.filters).$promise.then(function (response) {
                        $scope.totalTaskOrders = JSON.parse(response.headers["x-pagination"]).TotalCount;
                        $scope.taskorderCollection = response.data;
                        //console.log($scope.searchResults);
                    }, $scope.showError);
                },
```

On a regular search -- I see 1 call.
e.g.
 /taskorder/to/CPARSSearch?pageNumber=1&pageSize=10&search=wf&sortColumn=strTaskOrder_num&sortDirection=ASC

After using the pagination -- I see the same call made 2 times
e.g.
  /taskorder/to/CPARSSearch?pageNumber=1&pageSize=10&search=wf&sortColumn=strTaskOrder_num&sortDirection=ASC
 /taskorder/to/CPARSSearch?pageNumber=1&pageSize=10&search=wf&sortColumn=strTaskOrder_num&sortDirection=ASC

Am I not implementing the calls correctly or is this a bug? I've used angularUtils for 1.5 years but never noticed this scenario until now and it is universal throughout my entire application.

Any help would be great! Thanks! -- Overall we love using this tool for pagination~!

**Comment by michaelbromley** [comment]
Hi,

thanks for the report. I think I get what is happening... So when you do a search, the search itself triggers the HTTP call, and then since you were on some other page than page 1, the currentPage gets reset to 1, and triggers onPageChange.

I wouldn't say this is a bug, since `onPageChange` just invokes the function whenever a page changes. It doesn't care about anything other than that. Perhaps you could implement some of your own logic whereby within your `getTaskOrders` function, you can tell it when a search has been fired, and have it not fire a duplicate HTTP call.

Another option would be to implement some kind of debouncing in the `taskOrder.query()` method.

I guess there are a number of ways to solve this depending on exactly how your code is set up. You may also find some useful info in this thread https://github.com/michaelbromley/angularUtils/issues/318.

**Comment by augustjared1** [comment]
Hi,

Thanks for the tips. I'm going to try some of the suggestions in thread #318 and see how that goes. I didn't see that thread before now. 

Thanks for the response!
