### ISSUE TITLE
hi, i want to implement re-arrange column in this directive so please help me

### ISSUE THREAD

**Issue by rahi-rajeev** [michaelbromley/angularUtils#422]
Hi, thanks for contributing!

This project is maintained in my spare time, so in order to help me address your issue as quickly as 
possible, please provide as much of the following information as you can:

- Title: Please indicate the module in question, e.g. "dirPagination: X is broken when Y"
- If reporting on dirPagination, please include the version you are using (can be found in the package.json / bower.json file)
- If you are able to reproduce your issue on Plunker, this will vastly increase the chances of a rapid response from me.

-- Michael 

=======
(Delete the above. Fill in the rest as applicable)

**Description of issue**:

**Steps to reproduce**:

**Expected result**:

**Actual result**:

**Demo**: (for dirPagination, fork and modify this Plunk: http://plnkr.co/edit/b37IdFFJUokaeSummETX?p=preview)

Any relevant code:
```

```

**Comment by rahi-rajeev** [comment]
i using this directive for server side table pagination so i want o implement there several functionality like
resize columns rearrange columns drag row so please help me

**Comment by michaelbromley** [comment]
Hi,

From what I understand of your request, you want help with some general UI problems. An issue in this repo is specifically for bug reports or feature requests pertaining to the library `angularUtils`, rather than general programming questions.

I kindly suggest you try one of the following:

1. Ask a colleague or friend who might know.
2. Find a forum where programmers hang out - e.g. on Reddit and ask there.
3. Do more research into possible pre-built solutions, for example I just searched on Google and found something that you could use: http://swimlane.github.io/angular-data-table/

**Comment by rahi-rajeev** [comment]
thanks but you now need to change all code as per as data table
