### ISSUE TITLE
on-page-changed called twice with 2 controls on the page

### ISSUE THREAD

**Issue by aishasims** [michaelbromley/angularUtils#81]
I have 1 collection that uses 2 controls (1 on top of the table, 1 on the bottom of the table). The 2 controls are for the same collection.  My issue is that the on-page-change event gets called twice when I click on a page #.  When I remove one of the controls it works fine, but I need to have both controls on the page.  Thoughts?

**Comment by craigcabrey** [comment]
I realize this is an old issue, but perhaps you could add a note to the `README` about this?

I ran into this same issue and was puzzled until I eventually stumbled upon this issue.

**Comment by michaelbromley** [comment]
@craigcabrey Just took another look at this and realized that you can also just remove the `on-page-change` attribute from *one* of the pagination controls directives, and it should fix the double callback issue.

Not sure if it is a frequent enough issue to warrant going in the readme. On reflection it almost seems expected that specifying the callback in two locations leads to it being called twice (yes, I know that things are easier to understand "on reflection" ;) )

In any case, this issue is well-named and hopefully who run into this will search the issues and find this without too much trouble.

**Comment by himanshupathakpwd** [comment]
Working fine when removed on-page-change from one directive. 

Thanks,
