### ISSUE TITLE
uiBreadcrumbs backspace + user not found

### ISSUE THREAD

**Issue by GoNode5** [michaelbromley/angularUtils#99]
Chrome browser / windows 8.1 latest
In the pluncker demo, backspace key doesnt seem to work. And if i go to image and click the back button 
I get in in the breadcrumb user not found.

**Comment by michaelbromley** [comment]
Yeah I noticed this too. I'm pretty sure it's due to a change in the workings of the newer version of UI router. I ill-advisedly made use of an internal API (`$state.$current` as opposed to the public `$state.current`) for the functionality you describe. 

I'm away on holiday for the next couple of weeks so I'll probably not get round to fixing this till I get back, but I do intend to bring it up to date with the latest ui-router version.

**Comment by GoNode5** [comment]
ok thanks  no problem just want to be sure it was not a problem on my side.

**Comment by michaelbromley** [comment]
I've updated the repo to the latest version of ui-router (0.2.13). All the tests work still, so it looks all fine. I fixed the Plunker demo so that the "not found" error is fixed. Regarding backspace not working, I think this may be a problem caused by running it inside Plunker. In a production app where I use this directive, backspace works fine.

**Comment by GoNode5** [comment]
Thank you, using succesfully (including backspace) with  Angular 1.3.10 ui router 0.2.13.
